name: Ping API

on:
  schedule:
    - cron: "*/5 * * * *"   # รันทุก 5 นาที (UTC)
  workflow_dispatch:

concurrency:
  group: ping-api
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Call API
        run: |
          response=$(curl -s -w "HTTPSTATUS:%{http_code}" -X POST https://api.kiddy.wtf/ \
            -H "Content-Type: application/json" \
            -d '{"mobile":"0000000000","voucher":"ping"}')

          body=$(echo "$response" | sed -e 's/HTTPSTATUS\:.*//g')
          status=$(echo "$response" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
          ts=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          if [ "$status" -eq 200 ]; then
            echo "✅ OK - Status: $status - $ts"
            # ส่งแจ้ง Discord ทุกครั้ง (Success)
            if [ -n "$DISCORD_WEBHOOK" ]; then
              curl -H "Content-Type: application/json" \
                   -d "{\"content\":\"✅ OK - Status: $status - $ts\"}" \
                   "$DISCORD_WEBHOOK"
            fi
          else
            echo "⚠️ FAIL - Status: $status - $ts"
            echo "Body: $body"
            # แจ้ง Discord เวลา Fail
            if [ -n "$DISCORD_WEBHOOK" ]; then
              curl -H "Content-Type: application/json" \
                   -d "{\"content\":\"⚠️ FAIL - Status: $status - $ts\nBody: $(echo "$body" | head -c 150)\"}" \
                   "$DISCORD_WEBHOOK"
            fi
            exit 1
          fi
