name: Keep Render Awake

on:
  schedule:
    - cron: "*/5 * * * *"   # รันทุก 5 นาที (UTC)
  workflow_dispatch: {}      # กด Run workflow เองได้

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping API with POST
        run: |
          curl -X POST "https://api.kiddy.wtf/" \
            -H "Content-Type: application/json" \
            -d '{"mobile":"0000000000","voucher":"ping"}'
