name: Ping API

on:
  schedule:
    - cron: "* * * * *"   # รันทุก 1 นาที (UTC)
  workflow_dispatch:

# กันงานคาบเกี่ยว ถ้ายังรันไม่เสร็จในรอบก่อน
concurrency:
  group: ping-api
  cancel-in-progress: false

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: |
          response=$(curl -s -w "HTTPSTATUS:%{http_code}" -X POST https://api.kiddy.wtf/ \
            -H "Content-Type: application/json" \
            -d '{"mobile":"0000000000","voucher":"ping"}')

          # แยก body กับ status code
          body=$(echo "$response" | sed -e 's/HTTPSTATUS\:.*//g')
          status=$(echo "$response" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')

          if [ "$status" -eq 200 ]; then
            echo "✅ OK - Status: $status - $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
          else
            echo "⚠️ FAIL - Status: $status - $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            echo "Body: $body"
            exit 1
          fi
